require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NfersController do

  # This should return the minimal set of attributes required to create a valid
  # Nfer. As you add validations to Nfer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "subject" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NfersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all nfers as @nfers" do
      nfer = Nfer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:nfers).should eq([nfer])
    end
  end

  describe "GET show" do
    it "assigns the requested nfer as @nfer" do
      nfer = Nfer.create! valid_attributes
      get :show, {:id => nfer.to_param}, valid_session
      assigns(:nfer).should eq(nfer)
    end
  end

  describe "GET new" do
    it "assigns a new nfer as @nfer" do
      get :new, {}, valid_session
      assigns(:nfer).should be_a_new(Nfer)
    end
  end

  describe "GET edit" do
    it "assigns the requested nfer as @nfer" do
      nfer = Nfer.create! valid_attributes
      get :edit, {:id => nfer.to_param}, valid_session
      assigns(:nfer).should eq(nfer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Nfer" do
        expect {
          post :create, {:nfer => valid_attributes}, valid_session
        }.to change(Nfer, :count).by(1)
      end

      it "assigns a newly created nfer as @nfer" do
        post :create, {:nfer => valid_attributes}, valid_session
        assigns(:nfer).should be_a(Nfer)
        assigns(:nfer).should be_persisted
      end

      it "redirects to the created nfer" do
        post :create, {:nfer => valid_attributes}, valid_session
        response.should redirect_to(Nfer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nfer as @nfer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nfer.any_instance.stub(:save).and_return(false)
        post :create, {:nfer => { "subject" => "invalid value" }}, valid_session
        assigns(:nfer).should be_a_new(Nfer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nfer.any_instance.stub(:save).and_return(false)
        post :create, {:nfer => { "subject" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nfer" do
        nfer = Nfer.create! valid_attributes
        # Assuming there are no other nfers in the database, this
        # specifies that the Nfer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Nfer.any_instance.should_receive(:update_attributes).with({ "subject" => "1" })
        put :update, {:id => nfer.to_param, :nfer => { "subject" => "1" }}, valid_session
      end

      it "assigns the requested nfer as @nfer" do
        nfer = Nfer.create! valid_attributes
        put :update, {:id => nfer.to_param, :nfer => valid_attributes}, valid_session
        assigns(:nfer).should eq(nfer)
      end

      it "redirects to the nfer" do
        nfer = Nfer.create! valid_attributes
        put :update, {:id => nfer.to_param, :nfer => valid_attributes}, valid_session
        response.should redirect_to(nfer)
      end
    end

    describe "with invalid params" do
      it "assigns the nfer as @nfer" do
        nfer = Nfer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nfer.any_instance.stub(:save).and_return(false)
        put :update, {:id => nfer.to_param, :nfer => { "subject" => "invalid value" }}, valid_session
        assigns(:nfer).should eq(nfer)
      end

      it "re-renders the 'edit' template" do
        nfer = Nfer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nfer.any_instance.stub(:save).and_return(false)
        put :update, {:id => nfer.to_param, :nfer => { "subject" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nfer" do
      nfer = Nfer.create! valid_attributes
      expect {
        delete :destroy, {:id => nfer.to_param}, valid_session
      }.to change(Nfer, :count).by(-1)
    end

    it "redirects to the nfers list" do
      nfer = Nfer.create! valid_attributes
      delete :destroy, {:id => nfer.to_param}, valid_session
      response.should redirect_to(nfers_url)
    end
  end

end
